kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: lim-pvc
  namespace: fortify
  labels:
    vol: lim-pvc
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
