apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortify-manager-observer
  namespace: fortify
---
apiVersion: v1
kind: Secret
metadata:
  name: fortify-manager-observer-token
  namespace: fortify
  annotations:
    kubernetes.io/service-account.name: fortify-manager-observer
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fortify-manager-observer
  namespace: fortify
rules:
  - apiGroups: [""]
    resources: [services]
    verbs: [get, list]
  - apiGroups: [apps]
    resources: [deployments, statefulsets]
    verbs: [get, list]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fortify-manager-observer
  namespace: fortify
subjects:
  - kind: ServiceAccount
    name: fortify-manager-observer
    namespace: fortify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fortify-manager-observer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fortify-manager-observer-discovery
rules:
  - nonResourceURLs: [/version]
    verbs: [get]
  - apiGroups: [""]
    resources: [nodes]
    verbs: [get, list]
  - apiGroups: [storage.k8s.io]
    resources: [storageclasses]
    verbs: [get, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fortify-manager-observer-discovery
subjects:
  - kind: ServiceAccount
    name: fortify-manager-observer
    namespace: fortify
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fortify-manager-observer-discovery
